//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RauCuQuaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANH
    {
        public string MAANH { get; set; }
        public string URL { get; set; }
        public string MASP { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
