//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RauCuQuaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MAHD { get; set; }
        public string MASP { get; set; }
        public string MAKL { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual khoiluong khoiluong { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
