//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RauCuQuaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhgia
    {
        public string MASP { get; set; }
        public string MATK { get; set; }
        public string ND { get; set; }
        public Nullable<int> SO_SAO { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
