//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RauCuQuaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttgiaohang
    {
        public string MATT { get; set; }
        public string SDT { get; set; }
        public string TINH { get; set; }
        public string THANHPHO { get; set; }
        public string QUANHUYEN { get; set; }
        public string XAPHUONG { get; set; }
        public string DIACHI { get; set; }
        public string MATK { get; set; }
    
        public virtual taikhoan taikhoan { get; set; }
    }
}
